Add some default tags to distinguish infrastructure
wellcomecollection/archivematica-infrastructure pull request #83
Opened 2021-06-25 10:38 UTC by kenoir

### What is this PR trying to achieve?

In order to easily distinguish Archivematica infrastructure in the workflow AWS this change adds [default tags](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider).

### Who is this change for?

For folk who want to be able to identify infra spend by project and make it easier for devs to understand infra in AWS.

2021-06-25 10:43 UTC, kenoir commented
The choice of tags comes from a useful subset of the [D&T tagging policy](https://wellcometrust.atlassian.net/wiki/spaces/INF/pages/300646401/Tagging+Policy), and adds our own terraform config location tag.

There should be enough detail in those tags for someone in D&T to work out _who_ is responsible for this infra.

2021-06-25 10:54 UTC, alexwlchan requested changes

2021-06-25 10:54 UTC, alexwlchan commented on terraform/critical_prod/provider.tf
> +      TerraformConfigurationURL = "https://github.com/wellcomecollection/goobi-infrastructure/tree/master/terraform/critical_prod"
goobi-infrastructure?

2021-06-28 09:06 UTC, alexwlchan approved these changes

2021-06-28 10:35 UTC, kenoir commented
This is applied.

2021-06-28 10:49 UTC, merged